//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input System/MasterInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MasterInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MasterInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MasterInput"",
    ""maps"": [
        {
            ""name"": ""PlayerControlDungeon"",
            ""id"": ""842cae48-b2e0-4f9e-bb65-ceb688534142"",
            ""actions"": [
                {
                    ""name"": ""MoveLeftRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6560cd02-ee1a-4a0a-a08e-713f9f800fd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2e4a3698-eaeb-4483-823e-d75d2ea6de57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmAnswer"",
                    ""type"": ""Button"",
                    ""id"": ""fdfa62dc-d915-441f-9395-802b198e4cc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClearAnswer"",
                    ""type"": ""Button"",
                    ""id"": ""56a0d206-7354-449b-a0e0-be21ac0e04ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponArt"",
                    ""type"": ""Button"",
                    ""id"": ""840b67de-5234-401c-a969-f7e635d5d129"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""03c9dda6-437e-477f-ad11-9f9e03bd4779"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""af0f66c4-80a7-4801-a1a1-43c1b669dd39"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3cebcfa4-e1d5-480f-a0a4-fe70f95be42e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3843218c-3137-4a95-b1a2-5e050fc82252"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""799d8b6a-c3bb-439d-991d-fd58c745f912"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmAnswer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""370e0bfa-c30c-48d5-8793-2540c2998af0"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmAnswer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ec54e8a-69ad-4f44-8f3d-d9196c23c266"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmAnswer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2315f6ce-fcc8-4d04-9d73-25aac0153f05"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponArt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be593045-a56a-484c-b906-9c9ee5ce2511"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearAnswer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerControlGeneral"",
            ""id"": ""a955f81a-466e-46f2-9699-474cecb18e67"",
            ""actions"": [
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""8041132b-c0f1-4bcf-913d-af7ed0fffcc2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextDialog"",
                    ""type"": ""Button"",
                    ""id"": ""b4499962-99ff-4757-868a-00710ca5d9e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93584668-50db-417f-abba-8bf081e0af2e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""120ab47e-f3a2-4132-82f3-a6c5bd9ad108"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a18c0c56-1280-4aef-8c85-5beac729759c"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerControlExploration"",
            ""id"": ""00064fd6-8ab7-408a-82e0-8ce50573dbb9"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""694d00e6-b08c-457b-9cbd-19f065763901"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUpdown"",
                    ""type"": ""PassThrough"",
                    ""id"": ""89e11989-8d1d-4e8c-9614-7798db898ebc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeftRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b05c1e2e-b740-4f9d-b0e7-f0e17ef49040"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""af45669a-748d-4b4d-a95c-1d9b286b7575"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1e887a0a-2755-4fd1-bb40-99c9523a188b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpdown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""96e024b9-7132-4156-9b2f-40f43f47cbcf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpdown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3a2ba436-0c89-40b1-858f-b9c2e52880f9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUpdown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""889a35cb-971d-4691-a939-2945543b7638"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b53fa372-d2d8-4e5a-930f-35fe61f32164"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4ec1e644-ced9-4e71-80ca-bb02d3726ee0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerControlElimination"",
            ""id"": ""66507642-8aa9-48e2-8497-6acf4985e772"",
            ""actions"": [
                {
                    ""name"": ""EnterAnswer"",
                    ""type"": ""Button"",
                    ""id"": ""3eb0adb7-e91d-44a1-bb64-bbd36d77c74c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClearAnswer"",
                    ""type"": ""Button"",
                    ""id"": ""5e8fd122-b929-498a-869c-ef793734d1f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchEnemy"",
                    ""type"": ""Button"",
                    ""id"": ""6b21754b-9cb5-44e5-92b5-ea73c24c45a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7a3b993-33a9-4d2c-8812-58e6be0ad2ea"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterAnswer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cc321cd-81fc-444f-ab66-618e16c98b02"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearAnswer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d4fea7c-25a5-4261-b3b8-2fe2af7ef664"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard Control"",
            ""bindingGroup"": ""Keyboard Control"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerControlDungeon
        m_PlayerControlDungeon = asset.FindActionMap("PlayerControlDungeon", throwIfNotFound: true);
        m_PlayerControlDungeon_MoveLeftRight = m_PlayerControlDungeon.FindAction("MoveLeftRight", throwIfNotFound: true);
        m_PlayerControlDungeon_Jump = m_PlayerControlDungeon.FindAction("Jump", throwIfNotFound: true);
        m_PlayerControlDungeon_ConfirmAnswer = m_PlayerControlDungeon.FindAction("ConfirmAnswer", throwIfNotFound: true);
        m_PlayerControlDungeon_ClearAnswer = m_PlayerControlDungeon.FindAction("ClearAnswer", throwIfNotFound: true);
        m_PlayerControlDungeon_WeaponArt = m_PlayerControlDungeon.FindAction("WeaponArt", throwIfNotFound: true);
        // PlayerControlGeneral
        m_PlayerControlGeneral = asset.FindActionMap("PlayerControlGeneral", throwIfNotFound: true);
        m_PlayerControlGeneral_PauseGame = m_PlayerControlGeneral.FindAction("PauseGame", throwIfNotFound: true);
        m_PlayerControlGeneral_NextDialog = m_PlayerControlGeneral.FindAction("NextDialog", throwIfNotFound: true);
        // PlayerControlExploration
        m_PlayerControlExploration = asset.FindActionMap("PlayerControlExploration", throwIfNotFound: true);
        m_PlayerControlExploration_Interact = m_PlayerControlExploration.FindAction("Interact", throwIfNotFound: true);
        m_PlayerControlExploration_MoveUpdown = m_PlayerControlExploration.FindAction("MoveUpdown", throwIfNotFound: true);
        m_PlayerControlExploration_MoveLeftRight = m_PlayerControlExploration.FindAction("MoveLeftRight", throwIfNotFound: true);
        // PlayerControlElimination
        m_PlayerControlElimination = asset.FindActionMap("PlayerControlElimination", throwIfNotFound: true);
        m_PlayerControlElimination_EnterAnswer = m_PlayerControlElimination.FindAction("EnterAnswer", throwIfNotFound: true);
        m_PlayerControlElimination_ClearAnswer = m_PlayerControlElimination.FindAction("ClearAnswer", throwIfNotFound: true);
        m_PlayerControlElimination_SwitchEnemy = m_PlayerControlElimination.FindAction("SwitchEnemy", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControlDungeon
    private readonly InputActionMap m_PlayerControlDungeon;
    private IPlayerControlDungeonActions m_PlayerControlDungeonActionsCallbackInterface;
    private readonly InputAction m_PlayerControlDungeon_MoveLeftRight;
    private readonly InputAction m_PlayerControlDungeon_Jump;
    private readonly InputAction m_PlayerControlDungeon_ConfirmAnswer;
    private readonly InputAction m_PlayerControlDungeon_ClearAnswer;
    private readonly InputAction m_PlayerControlDungeon_WeaponArt;
    public struct PlayerControlDungeonActions
    {
        private @MasterInput m_Wrapper;
        public PlayerControlDungeonActions(@MasterInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveLeftRight => m_Wrapper.m_PlayerControlDungeon_MoveLeftRight;
        public InputAction @Jump => m_Wrapper.m_PlayerControlDungeon_Jump;
        public InputAction @ConfirmAnswer => m_Wrapper.m_PlayerControlDungeon_ConfirmAnswer;
        public InputAction @ClearAnswer => m_Wrapper.m_PlayerControlDungeon_ClearAnswer;
        public InputAction @WeaponArt => m_Wrapper.m_PlayerControlDungeon_WeaponArt;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControlDungeon; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlDungeonActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlDungeonActions instance)
        {
            if (m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface != null)
            {
                @MoveLeftRight.started -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.performed -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.canceled -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnMoveLeftRight;
                @Jump.started -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnJump;
                @ConfirmAnswer.started -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnConfirmAnswer;
                @ConfirmAnswer.performed -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnConfirmAnswer;
                @ConfirmAnswer.canceled -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnConfirmAnswer;
                @ClearAnswer.started -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnClearAnswer;
                @ClearAnswer.performed -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnClearAnswer;
                @ClearAnswer.canceled -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnClearAnswer;
                @WeaponArt.started -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnWeaponArt;
                @WeaponArt.performed -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnWeaponArt;
                @WeaponArt.canceled -= m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface.OnWeaponArt;
            }
            m_Wrapper.m_PlayerControlDungeonActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveLeftRight.started += instance.OnMoveLeftRight;
                @MoveLeftRight.performed += instance.OnMoveLeftRight;
                @MoveLeftRight.canceled += instance.OnMoveLeftRight;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @ConfirmAnswer.started += instance.OnConfirmAnswer;
                @ConfirmAnswer.performed += instance.OnConfirmAnswer;
                @ConfirmAnswer.canceled += instance.OnConfirmAnswer;
                @ClearAnswer.started += instance.OnClearAnswer;
                @ClearAnswer.performed += instance.OnClearAnswer;
                @ClearAnswer.canceled += instance.OnClearAnswer;
                @WeaponArt.started += instance.OnWeaponArt;
                @WeaponArt.performed += instance.OnWeaponArt;
                @WeaponArt.canceled += instance.OnWeaponArt;
            }
        }
    }
    public PlayerControlDungeonActions @PlayerControlDungeon => new PlayerControlDungeonActions(this);

    // PlayerControlGeneral
    private readonly InputActionMap m_PlayerControlGeneral;
    private IPlayerControlGeneralActions m_PlayerControlGeneralActionsCallbackInterface;
    private readonly InputAction m_PlayerControlGeneral_PauseGame;
    private readonly InputAction m_PlayerControlGeneral_NextDialog;
    public struct PlayerControlGeneralActions
    {
        private @MasterInput m_Wrapper;
        public PlayerControlGeneralActions(@MasterInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseGame => m_Wrapper.m_PlayerControlGeneral_PauseGame;
        public InputAction @NextDialog => m_Wrapper.m_PlayerControlGeneral_NextDialog;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControlGeneral; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlGeneralActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlGeneralActions instance)
        {
            if (m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface != null)
            {
                @PauseGame.started -= m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface.OnPauseGame;
                @NextDialog.started -= m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface.OnNextDialog;
                @NextDialog.performed -= m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface.OnNextDialog;
                @NextDialog.canceled -= m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface.OnNextDialog;
            }
            m_Wrapper.m_PlayerControlGeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @NextDialog.started += instance.OnNextDialog;
                @NextDialog.performed += instance.OnNextDialog;
                @NextDialog.canceled += instance.OnNextDialog;
            }
        }
    }
    public PlayerControlGeneralActions @PlayerControlGeneral => new PlayerControlGeneralActions(this);

    // PlayerControlExploration
    private readonly InputActionMap m_PlayerControlExploration;
    private IPlayerControlExplorationActions m_PlayerControlExplorationActionsCallbackInterface;
    private readonly InputAction m_PlayerControlExploration_Interact;
    private readonly InputAction m_PlayerControlExploration_MoveUpdown;
    private readonly InputAction m_PlayerControlExploration_MoveLeftRight;
    public struct PlayerControlExplorationActions
    {
        private @MasterInput m_Wrapper;
        public PlayerControlExplorationActions(@MasterInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_PlayerControlExploration_Interact;
        public InputAction @MoveUpdown => m_Wrapper.m_PlayerControlExploration_MoveUpdown;
        public InputAction @MoveLeftRight => m_Wrapper.m_PlayerControlExploration_MoveLeftRight;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControlExploration; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlExplorationActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlExplorationActions instance)
        {
            if (m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface != null)
            {
                @Interact.started -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnInteract;
                @MoveUpdown.started -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnMoveUpdown;
                @MoveUpdown.performed -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnMoveUpdown;
                @MoveUpdown.canceled -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnMoveUpdown;
                @MoveLeftRight.started -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.performed -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.canceled -= m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface.OnMoveLeftRight;
            }
            m_Wrapper.m_PlayerControlExplorationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @MoveUpdown.started += instance.OnMoveUpdown;
                @MoveUpdown.performed += instance.OnMoveUpdown;
                @MoveUpdown.canceled += instance.OnMoveUpdown;
                @MoveLeftRight.started += instance.OnMoveLeftRight;
                @MoveLeftRight.performed += instance.OnMoveLeftRight;
                @MoveLeftRight.canceled += instance.OnMoveLeftRight;
            }
        }
    }
    public PlayerControlExplorationActions @PlayerControlExploration => new PlayerControlExplorationActions(this);

    // PlayerControlElimination
    private readonly InputActionMap m_PlayerControlElimination;
    private IPlayerControlEliminationActions m_PlayerControlEliminationActionsCallbackInterface;
    private readonly InputAction m_PlayerControlElimination_EnterAnswer;
    private readonly InputAction m_PlayerControlElimination_ClearAnswer;
    private readonly InputAction m_PlayerControlElimination_SwitchEnemy;
    public struct PlayerControlEliminationActions
    {
        private @MasterInput m_Wrapper;
        public PlayerControlEliminationActions(@MasterInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @EnterAnswer => m_Wrapper.m_PlayerControlElimination_EnterAnswer;
        public InputAction @ClearAnswer => m_Wrapper.m_PlayerControlElimination_ClearAnswer;
        public InputAction @SwitchEnemy => m_Wrapper.m_PlayerControlElimination_SwitchEnemy;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControlElimination; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlEliminationActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlEliminationActions instance)
        {
            if (m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface != null)
            {
                @EnterAnswer.started -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnEnterAnswer;
                @EnterAnswer.performed -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnEnterAnswer;
                @EnterAnswer.canceled -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnEnterAnswer;
                @ClearAnswer.started -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnClearAnswer;
                @ClearAnswer.performed -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnClearAnswer;
                @ClearAnswer.canceled -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnClearAnswer;
                @SwitchEnemy.started -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnSwitchEnemy;
                @SwitchEnemy.performed -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnSwitchEnemy;
                @SwitchEnemy.canceled -= m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface.OnSwitchEnemy;
            }
            m_Wrapper.m_PlayerControlEliminationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EnterAnswer.started += instance.OnEnterAnswer;
                @EnterAnswer.performed += instance.OnEnterAnswer;
                @EnterAnswer.canceled += instance.OnEnterAnswer;
                @ClearAnswer.started += instance.OnClearAnswer;
                @ClearAnswer.performed += instance.OnClearAnswer;
                @ClearAnswer.canceled += instance.OnClearAnswer;
                @SwitchEnemy.started += instance.OnSwitchEnemy;
                @SwitchEnemy.performed += instance.OnSwitchEnemy;
                @SwitchEnemy.canceled += instance.OnSwitchEnemy;
            }
        }
    }
    public PlayerControlEliminationActions @PlayerControlElimination => new PlayerControlEliminationActions(this);
    private int m_KeyboardControlSchemeIndex = -1;
    public InputControlScheme KeyboardControlScheme
    {
        get
        {
            if (m_KeyboardControlSchemeIndex == -1) m_KeyboardControlSchemeIndex = asset.FindControlSchemeIndex("Keyboard Control");
            return asset.controlSchemes[m_KeyboardControlSchemeIndex];
        }
    }
    public interface IPlayerControlDungeonActions
    {
        void OnMoveLeftRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnConfirmAnswer(InputAction.CallbackContext context);
        void OnClearAnswer(InputAction.CallbackContext context);
        void OnWeaponArt(InputAction.CallbackContext context);
    }
    public interface IPlayerControlGeneralActions
    {
        void OnPauseGame(InputAction.CallbackContext context);
        void OnNextDialog(InputAction.CallbackContext context);
    }
    public interface IPlayerControlExplorationActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnMoveUpdown(InputAction.CallbackContext context);
        void OnMoveLeftRight(InputAction.CallbackContext context);
    }
    public interface IPlayerControlEliminationActions
    {
        void OnEnterAnswer(InputAction.CallbackContext context);
        void OnClearAnswer(InputAction.CallbackContext context);
        void OnSwitchEnemy(InputAction.CallbackContext context);
    }
}
